# Generated by Django 6.0.1 on 2026-01-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='estado',
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
