# Generated by Django 6.0.1 on 2026-02-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_proveedor_licencia_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='unidad_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
