# Generated by Django 6.0.1 on 2026-02-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0005_asignacion_unidad_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'ordering': ['-fecha_asignacion']},
        ),
    ]
