# Generated by Django 6.0.1 on 2026-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0006_alter_asignacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, help_text='Nombre del contacto comercial o email', max_length=100, null=True),
        ),
    ]
