# Generated by Django 6.0.1 on 2026-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0007_alter_proveedor_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
