# Generated by Django 6.0.1 on 2026-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0007_alter_proveedor_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
    ]
