# Generated by Django 4.2.11 on 2026-05-25 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0008_empresa_activo_tenant_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='licencias.proveedor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_vencimiento', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencias.empresa')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='licencias.factura')),
                ('tipo_licencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencias.tipolicencia')),
            ],
        ),
    ]
