# Generated by Django 6.0.1 on 2026-05-26 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0008_empresa_activo_tenant_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestaLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número de Propuesta')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas', to='licencias.empresa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePropuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Precio ofertado en la propuesta', max_digits=12)),
                ('tipo_licencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencias.tipolicencia')),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='licencias.propuestalicencia')),
            ],
        ),
    ]
