# Generated by Django 6.0.1 on 2026-05-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0008_empresa_activo_licencia_activo_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipolicencia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
    ]
