# Generated by Django 6.0.1 on 2026-05-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0008_empresa_activo_tenant_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
