# Generated by Django 4.2.11 on 2026-05-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0009_factura_detallefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio por unidad de licencia (en USD o moneda local)', max_digits=12),
        ),
    ]
