# Generated by Django 6.0.1 on 2026-05-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0009_tenant_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
