# Generated by Django 6.0.1 on 2026-05-27 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0010_detallefactura_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True, verbose_name='Número de Nota de Alquiler')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento_pago', models.DateField(help_text='Fecha límite para el pago del alquiler')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENCIMIENTO_PAGO', 'Vencimiento de Pago de Alquiler'), ('LIMITE_CONTRATO', 'Fecha Límite de Licencia')], max_length=30)),
                ('fecha_alerta', models.DateField(help_text='Fecha en la que debe saltar o mostrarse la alerta')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Alerta Pendiente'), ('ENVIADA', 'Notificación Despachada'), ('PROCESADA', 'Atendida / Solucionada')], default='PENDIENTE', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('referencia_nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licencias.notaalquiler')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='licencias.notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada / Confirmada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencias.empresa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='notaalquiler',
            name='propuesta',
            field=models.OneToOneField(help_text='Propuesta comercial que origina este cierre operativo', on_delete=django.db.models.deletion.PROTECT, related_name='nota_alquiler', to='licencias.propuestalicencia'),
        ),
    ]
