# Generated by Django 6.0.1 on 2026-05-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0010_inventario_trazabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(help_text='Nombre comercial.', max_length=100, unique=True),
        ),
    ]
