# Generated by Django 6.0.1 on 2026-05-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0010_alter_tenant_numero'),
        ('licencias', '0010_inventario_trazabilidad'),
    ]

    operations = [
    ]
