# Generated by Django 6.0.1 on 2026-06-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0011_alter_proveedor_nombre'),
        ('licencias', '0011_licencia_precios'),
    ]

    operations = [
    ]
