# Generated by Django 6.0.1 on 2026-06-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0009_tipolicencia_activo'),
        ('licencias', '0012_merge_20260621_1230'),
    ]

    operations = [
    ]
