# Generated by Django 6.0.1 on 2026-05-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_estados_borrador_anulada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propuestalicencia',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Cotizacion', 'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
