# Generated by Django 6.0.1 on 2026-06-26 04:34

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def crear_pagos_historicos(apps, schema_editor):
    Factura = apps.get_model('facturacion', 'Factura')
    DetalleFactura = apps.get_model('facturacion', 'DetalleFactura')
    PagoFactura = apps.get_model('facturacion', 'PagoFactura')

    for factura in Factura.objects.filter(estado='PAGADA').iterator():
        subtotal = Decimal('0')
        for detalle in DetalleFactura.objects.filter(factura_id=factura.id):
            bruto = Decimal(str(detalle.cantidad)) * Decimal(str(detalle.precio_unitario or 0))
            descuento_pct = Decimal(str(detalle.descuento_porcentaje or 0)) / Decimal('100')
            descuento_monto = Decimal(str(detalle.descuento_monto or 0))
            subtotal += bruto - ((bruto * descuento_pct) + descuento_monto)

        descuento_global = (
            subtotal * (Decimal(str(factura.descuento_porcentaje or 0)) / Decimal('100'))
        ) + Decimal(str(factura.descuento_monto or 0))
        neto = subtotal - descuento_global
        impuesto = neto * (Decimal(str(factura.impuesto_porcentaje or 0)) / Decimal('100'))
        total = neto + impuesto

        if total <= 0:
            continue

        PagoFactura.objects.create(
            factura_id=factura.id,
            fecha_pago=factura.fecha,
            monto=total,
            metodo_pago=factura.metodo_pago or 'OTRO',
            referencia='MIGRACION:PAGADA',
            observaciones='Pago historico creado automaticamente desde facturas ya marcadas como PAGADA.',
            estado='ACTIVO',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_propuestalicencia_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='factura',
                    name='estado',
                    field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGO_PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Credito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pagos/')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ANULADO', 'Anulado')], default='ACTIVO', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_facturacion', to=settings.AUTH_USER_MODEL)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
            ],
            options={
                'verbose_name': 'Pago de factura',
                'verbose_name_plural': 'Pagos de factura',
                'ordering': ['-fecha_pago', '-id'],
                'indexes': [models.Index(fields=['estado', 'fecha_pago'], name='facturacion_estado_7b8126_idx'), models.Index(fields=['metodo_pago', 'fecha_pago'], name='facturacion_metodo__0b6057_idx')],
            },
        ),
        migrations.RunPython(crear_pagos_historicos, migrations.RunPython.noop),
    ]
