# Generated by Django 6.0.1 on 2026-01-23 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GerenciaDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: GDO', max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gerencia de División',
                'verbose_name_plural': 'Gerencias de División',
            },
        ),
        migrations.CreateModel(
            name='GerenciaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: GHC', max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='empleados.gerenciadivision')),
            ],
            options={
                'verbose_name': 'Gerencia de Área',
                'verbose_name_plural': 'Gerencias de Área',
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='empleados.gerenciaarea')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('email_principal', models.EmailField(max_length=254, unique=True, verbose_name='User Principal Name')),
                ('pais', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=80)),
                ('puesto', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('oficina', models.CharField(max_length=80)),
                ('licencias_extras', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.gerenciaarea', verbose_name='Gerencia de Área')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empleados.gerenciadivision', verbose_name='Gerencia de División')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.unidad')),
            ],
        ),
    ]
