# Generated by Django 6.0.1 on 2026-01-26 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('licencias', '0003_empresa_licencia_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='licencias.empresa', verbose_name='Empresa'),
        ),
    ]
