# Generated by Django 6.0.1 on 2026-02-16 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_empresa'),
        ('licencias', '0003_empresa_licencia_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.AddField(
            model_name='gerenciaarea',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='licencias.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerenciadivision',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='licencias.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.gerenciadivision', verbose_name='Gerencia de División'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='licencias.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gerenciaarea',
            name='codigo',
            field=models.CharField(blank=True, help_text='Ej: MANT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gerenciadivision',
            name='codigo',
            field=models.CharField(help_text='Ej: GDO', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='gerenciadivision',
            unique_together={('empresa', 'codigo')},
        ),
    ]
