# Generated by Django 6.0.1 on 2026-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_empleado_departamento_gerenciaarea_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciaarea',
            name='codigo',
            field=models.CharField(blank=True, help_text='Ej: GHC', max_length=10, null=True),
        ),
    ]
