# Generated by Django 6.0.1 on 2026-02-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_gerenciaarea_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='centro_de_costos',
            field=models.CharField(blank=True, help_text='Ej: 102030 (Opcional)', max_length=20, null=True),
        ),
    ]
