# Generated by Django 6.0.1 on 2026-03-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_centro_de_costos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='licencias_extras',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(default='Santa Cruz de la Sierra', max_length=80),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='oficina',
            field=models.CharField(blank=True, help_text='Ej: Oficina Central, Planta Parque Industrial', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pais',
            field=models.CharField(default='Bolivia', max_length=30),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
