# Generated by Django 6.0.1 on 2026-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_remove_empleado_licencias_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='centro_de_costos',
            field=models.CharField(blank=True, help_text='Código del centro de costos asignado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email_principal',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico Principal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='oficina',
            field=models.CharField(blank=True, help_text='Ubicación física operativa', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gerenciaarea',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código identificador del área. Ej: GHC', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gerenciadivision',
            name='codigo',
            field=models.CharField(help_text='Código identificador de la división. Ej: GDO', max_length=10),
        ),
    ]
