# Generated by Django 6.0.1 on 2026-04-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_cargo'),
        ('user', '0005_areausuario_perfilusuario_area_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='area_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='user.areausuario'),
        ),
    ]
