# Generated by Django 6.0.1 on 2026-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_cargo_area_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerenciaarea',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gerenciadivision',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
