# Generated by Django 6.0.1 on 2026-05-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_gerenciaarea_activo_gerenciadivision_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='perfil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
