# Generated by Django 6.0.1 on 2026-04-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_cargo'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.cargo'),
        ),
    ]
