# Generated by Django 6.0.1 on 2026-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_perfilusuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='area',
            field=models.CharField(blank=True, choices=[('administracion', 'Administración'), ('soporte', 'Soporte'), ('operaciones', 'Operaciones'), ('auditoria', 'Auditoría'), ('sistemas', 'Sistemas'), ('cliente', 'Cliente')], max_length=40, null=True),
        ),
    ]
