# Generated by Django 6.0.1 on 2026-04-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_perfilusuario_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
