# Generated by Django 6.0.1 on 2026-04-16 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_perfilusuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Area de usuario',
                'verbose_name_plural': 'Areas de usuario',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='area_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='user.areausuario'),
        ),
    ]
