# Generated by Django 6.0.1 on 2026-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_seed_areausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
