# Generated by Django 6.0.1 on 2026-06-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_perfilusuario_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='recibir_alertas_vencimiento',
            field=models.BooleanField(default=False, help_text='Si esta marcado, este usuario recibira emails cuando haya licencias proximas a vencer.', verbose_name='Recibir alertas de vencimiento de licencias'),
        ),
    ]
