# Generated by Django 6.0.1 on 2026-05-26 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0011_empleado_perfil'),
        ('licencias', '0010_alter_tenant_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento_pago', models.DateField(help_text='Fecha límite de pago que disparará las alertas automáticas')),
                ('monto_pactado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido / En Mora')], default='PENDIENTE', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('ALERTA_VENCIMIENTO', 'Alerta de Vencimiento'), ('CIERRE_OPERATIVO', 'Confirmación de Cierre')], max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nota_alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cierres_operativos.notaalquiler')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('empleado_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cierres_operativos.notificacion')),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_propuesta', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licencias.empresa')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licencias.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='notaalquiler',
            name='propuesta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nota_alquiler', to='cierres_operativos.propuestacomercial'),
        ),
    ]
